version: "2"
services:
    cassandra:
      image: cassandra:3
      ports:
        - "7199:7199" # JMX
        - "7000:7000" # Internode
        - "7001:7001" # Internode (TLS)
        - "9160:9160" # Thrift client API
        - "9042:9042" # CQL Native transport
    rabbit:
      image: rabbitmq:3.6-management
      ports:
        - "5672:5672"
        - "15672:15672"
    development:
      image: karoku-docker-docker.bintray.io/docker-development:0.1.0
      build: .
      ports:
        - "8080:8080"
      links:
        - cassandra:cassandra
        - rabbit:rabbit
